# Generated by Django 5.2.5 on 2025-08-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_instrumentaverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentaverage',
            name='prom_meta',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='instrumentaverage',
            name='instrument',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
